USE online_shop;

insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (1, 'Zena', 'Eallis', 'zeallis0@reddit.com', 'Félicie', 'Recruiter', 1);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (2, 'Nyssa', 'Rodgman', 'nrodgman1@nba.com', 'Tú', 'Administrative Assistant IV', 2);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (3, 'Shalom', 'Rivaland', 'srivaland2@nbcnews.com', 'Camélia', 'Research Associate', 3);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (4, 'Colby', 'Cinavas', 'ccinavas3@multiply.com', 'Sélène', 'Electrical Engineer', 4);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (5, 'Murdock', 'Ewbank', 'mewbank4@home.pl', 'Personnalisée', 'Software Test Engineer IV', 5);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (6, 'Matthew', 'McGoon', 'mmcgoon5@bluehost.com', 'Fèi', 'Statistician I', 6);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (7, 'Josefina', 'Bowhey', 'jbowhey6@ocn.ne.jp', 'Marie-ève', 'Geologist IV', 7);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (8, 'Alfonso', 'Holley', 'aholley7@spotify.com', null, 'Director of Sales', 8);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (9, 'Clem', 'Blues', 'cblues8@umn.edu', 'Gösta', 'Systems Administrator II', 9);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (10, 'Tessa', 'Bloxsum', 'tbloxsum9@deviantart.com', null, 'VP Marketing', 10);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (11, 'Ramsey', 'Brophy', 'rbrophya@jalbum.net', 'Noëlla', 'Media Manager IV', 11);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (12, 'Kenton', 'Bibb', 'kbibbb@google.co.jp', 'Audréanne', 'Sales Associate', 12);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (13, 'Tripp', 'Shepeard', 'tshepeardc@technorati.com', 'Méghane', 'Chief Design Engineer', 13);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (14, 'Hector', 'Goard', 'hgoardd@guardian.co.uk', 'Lèi', 'Senior Developer', 14);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (15, 'Christos', 'Feavyour', 'cfeavyoure@jiathis.com', 'Maïwenn', 'Senior Quality Engineer', 15);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (16, 'Doll', 'Twiggs', 'dtwiggsf@yale.edu', 'Maëlyss', 'Analog Circuit Design manager', 16);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (17, 'Konstantine', 'Spare', 'kspareg@princeton.edu', null, 'Research Nurse', 17);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (18, 'Adorne', 'Steart', 'astearth@businesswire.com', 'Daphnée', 'Assistant Professor', 18);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (19, 'Asa', 'Labbe', 'alabbei@arizona.edu', 'Estée', 'Assistant Media Planner', 19);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (20, 'Linus', 'Oguz', 'loguzj@prweb.com', 'Cléopatre', 'Assistant Manager', 20);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (21, 'Sheffie', 'Larciere', 'slarcierek@tuttocitta.it', 'Görel', 'Help Desk Operator', 21);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (22, 'Wright', 'Tilmouth', 'wtilmouthl@disqus.com', 'Bénédicte', 'General Manager', 22);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (23, 'Masha', 'Anchor', 'manchorm@weibo.com', 'Adèle', 'Environmental Tech', 23);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (24, 'Powell', 'Malden', 'pmaldenn@ed.gov', 'Kallisté', 'Nurse', 24);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (25, 'Bree', 'McAllaster', 'bmcallastero@shareasale.com', 'Marie-josée', 'Information Systems Manager', 25);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (26, 'Nichole', 'Aldrin', 'naldrinp@ocn.ne.jp', 'Mélinda', 'Civil Engineer', 26);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (27, 'Duff', 'Murford', 'dmurfordq@whitehouse.gov', 'Josée', 'Design Engineer', 27);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (28, 'Mickie', 'Killough', 'mkilloughr@amazonaws.com', 'Rébecca', 'Compensation Analyst', 28);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (29, 'Ellyn', 'Trower', 'etrowers@instagram.com', 'Östen', 'Office Assistant IV', 29);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (30, 'Gun', 'Fincke', 'gfincket@bigcartel.com', 'Gérald', 'Recruiter', 30);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (31, 'Philippe', 'Ferreli', 'pferreliu@earthlink.net', 'Bénédicte', 'Food Chemist', 31);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (32, 'Andy', 'Blatchford', 'ablatchfordv@liveinternet.ru', 'Eugénie', 'Staff Scientist', 32);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (33, 'Kendal', 'Ozelton', 'kozeltonw@addtoany.com', 'Hélèna', 'Design Engineer', 33);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (34, 'Had', 'Stranger', 'hstrangerx@toplist.cz', 'Maëlla', 'Chief Design Engineer', 34);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (35, 'Shayne', 'Pantone', 'spantoney@bing.com', 'Maëlyss', 'Marketing Assistant', 35);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (36, 'Janie', 'Scrase', 'jscrasez@addthis.com', 'Personnalisée', 'Geologist III', 36);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (37, 'Agata', 'Gardner', 'agardner10@about.me', null, 'Biostatistician IV', 37);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (38, 'Shea', 'Cobello', 'scobello11@chronoengine.com', 'Rébecca', 'Actuary', 38);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (39, 'Barthel', 'De Zuani', 'bdezuani12@ow.ly', 'Maëlys', 'Graphic Designer', 39);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (40, 'Retha', 'Pierpoint', 'rpierpoint13@latimes.com', 'Méryl', 'Chief Design Engineer', 40);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (41, 'Gracia', 'Winny', 'gwinny14@auda.org.au', 'Séverine', 'Staff Scientist', 41);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (42, 'Florenza', 'Deathridge', 'fdeathridge15@cdc.gov', 'Rébecca', 'Assistant Manager', 42);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (43, 'Leila', 'Paice', 'lpaice16@cnbc.com', 'Vénus', 'VP Quality Control', 43);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (44, 'Renard', 'Donne', 'rdonne17@japanpost.jp', 'André', 'Geological Engineer', 44);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (45, 'Ileane', 'Johannesson', 'ijohannesson18@merriam-webster.com', 'Mén', 'Recruiting Manager', 45);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (46, 'Jehu', 'Asson', 'jasson19@mozilla.com', 'Yáo', 'Administrative Assistant II', 46);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (47, 'Saxe', 'Meagh', 'smeagh1a@ox.ac.uk', 'Bérénice', 'Structural Engineer', 47);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (48, 'Zelma', 'Fish', 'zfish1b@slate.com', 'Börje', 'Professor', 48);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (49, 'Katie', 'Raphael', 'kraphael1c@sourceforge.net', null, 'Project Manager', 49);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (50, 'Tori', 'Ricardou', 'tricardou1d@newyorker.com', 'Mélina', 'Associate Professor', 50);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (51, 'Jena', 'Billett', 'jbillett1e@google.cn', 'Mà', 'Data Coordinator', 51);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (52, 'Charles', 'Dineges', 'cdineges1f@instagram.com', null, 'Operator', 52);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (53, 'Caria', 'Valintine', 'cvalintine1g@businessweek.com', 'Eloïse', 'VP Product Management', 53);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (54, 'Lilias', 'Josiah', 'ljosiah1h@epa.gov', 'Måns', 'Sales Representative', 54);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (55, 'Jarrod', 'Longhirst', 'jlonghirst1i@edublogs.org', 'Lén', 'Compensation Analyst', 55);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (56, 'Lesley', 'MacKniely', 'lmackniely1j@biblegateway.com', 'Publicité', 'Research Assistant III', 56);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (57, 'Curtice', 'Mowat', 'cmowat1k@weibo.com', 'Réjane', 'VP Quality Control', 57);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (58, 'Row', 'Allabush', 'rallabush1l@cam.ac.uk', 'Sélène', 'Accounting Assistant I', 58);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (59, 'Dasie', 'Palatino', 'dpalatino1m@amazonaws.com', 'Cléopatre', 'Project Manager', 59);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (60, 'Jonis', 'Baylie', 'jbaylie1n@ocn.ne.jp', 'Maïté', 'Director of Sales', 60);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (61, 'Raphaela', 'Playhill', 'rplayhill1o@merriam-webster.com', 'Publicité', 'Nuclear Power Engineer', 61);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (62, 'Janeczka', 'Crose', 'jcrose1p@yandex.ru', 'Garçon', 'Quality Control Specialist', 62);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (63, 'Thain', 'Bricksey', 'tbricksey1q@pagesperso-orange.fr', 'Erwéi', 'Human Resources Assistant I', 63);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (64, 'Bartholomew', 'Whitelock', 'bwhitelock1r@mashable.com', 'Cinéma', 'Accounting Assistant I', 64);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (65, 'Shandy', 'Gossipin', 'sgossipin1s@unc.edu', 'Lucrèce', 'Account Representative I', 65);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (66, 'Charmain', 'Paniman', 'cpaniman1t@comcast.net', 'Simplifiés', 'Data Coordinator', 66);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (67, 'Elianore', 'Renahan', 'erenahan1u@home.pl', 'Pò', 'Developer II', 67);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (68, 'Robert', 'Guppy', 'rguppy1v@mail.ru', 'Ruò', 'Engineer II', 68);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (69, 'Rorie', 'GiacobbiniJacob', 'rgiacobbinijacob1w@telegraph.co.uk', 'Lóng', 'Community Outreach Specialist', 69);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (70, 'Salomi', 'Loughnan', 'sloughnan1x@yolasite.com', 'Maïlys', 'Design Engineer', 70);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (71, 'John', 'Flavelle', 'jflavelle1y@nydailynews.com', 'Stévina', 'Budget/Accounting Analyst III', 71);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (72, 'Aluin', 'Flatte', 'aflatte1z@g.co', 'Mégane', 'Research Nurse', 72);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (73, 'Trina', 'McCreery', 'tmccreery20@nytimes.com', 'Bérengère', 'Research Assistant IV', 73);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (74, 'Henrie', 'Ayce', 'hayce21@wired.com', 'Gaétane', 'Marketing Assistant', 74);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (75, 'Susanna', 'Siely', 'ssiely22@qq.com', 'Agnès', 'Clinical Specialist', 75);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (76, 'Jess', 'Furlow', 'jfurlow23@networksolutions.com', null, 'Payment Adjustment Coordinator', 76);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (77, 'Audrye', 'Poland', 'apoland24@odnoklassniki.ru', 'Lyséa', 'Marketing Assistant', 77);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (78, 'Dacia', 'Willoughby', 'dwilloughby25@ovh.net', 'Maëlyss', 'VP Product Management', 78);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (79, 'Alina', 'Quirke', 'aquirke26@miitbeian.gov.cn', 'Lyséa', 'Health Coach I', 79);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (80, 'Rollins', 'Vina', 'rvina27@oakley.com', 'Béatrice', 'Software Engineer I', 80);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (81, 'Tabbie', 'Chinn', 'tchinn28@bloomberg.com', 'Gisèle', 'Social Worker', 81);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (82, 'Nickey', 'Phipps', 'nphipps29@ocn.ne.jp', 'Maëlann', 'Nuclear Power Engineer', 82);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (83, 'Wye', 'Madeley', 'wmadeley2a@amazon.co.uk', 'Sélène', 'Accounting Assistant I', 83);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (84, 'Reginauld', 'Vooght', 'rvooght2b@gov.uk', 'Lèi', 'Marketing Manager', 84);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (85, 'Allyn', 'Burner', 'aburner2c@wordpress.com', 'Märta', 'Senior Sales Associate', 85);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (86, 'Zarah', 'Tilbury', 'ztilbury2d@meetup.com', 'Dorothée', 'Biostatistician I', 86);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (87, 'Lulu', 'McLafferty', 'lmclafferty2e@nature.com', 'Méghane', 'Senior Editor', 87);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (88, 'Brennan', 'Dacca', 'bdacca2f@moonfruit.com', 'Géraldine', 'Occupational Therapist', 88);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (89, 'Berk', 'Pach', 'bpach2g@va.gov', 'Kuí', 'Research Associate', 89);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (90, 'Otha', 'Mullin', 'omullin2h@dmoz.org', 'Josée', 'Budget/Accounting Analyst III', 90);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (91, 'Constanta', 'Jewess', 'cjewess2i@so-net.ne.jp', 'Clémence', 'Budget/Accounting Analyst II', 91);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (92, 'Deanne', 'Zwicker', 'dzwicker2j@csmonitor.com', 'Yè', 'Computer Systems Analyst IV', 92);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (93, 'Hazlett', 'Dunderdale', 'hdunderdale2k@elegantthemes.com', 'Noémie', 'Programmer Analyst IV', 93);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (94, 'Michail', 'Raoux', 'mraoux2l@zimbio.com', 'Rébecca', 'Software Consultant', 94);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (95, 'Osborne', 'Vicioso', 'ovicioso2m@netvibes.com', 'Mélinda', 'Operator', 95);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (96, 'Edward', 'Trask', 'etrask2n@shinystat.com', 'Bécassine', 'Project Manager', 96);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (97, 'Tessy', 'Keywood', 'tkeywood2o@desdev.cn', 'Mélys', 'Database Administrator III', 97);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (98, 'Janene', 'Dockerty', 'jdockerty2p@histats.com', 'Valérie', 'Media Manager I', 98);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (99, 'Bernadette', 'Day', 'bday2q@jimdo.com', 'Laurélie', 'Nurse Practicioner', 99);
insert into Employee (employee_id, first_name, last_name, email, middle_name, role, StoreID) values (100, 'Care', 'Happs', 'chapps2r@ebay.co.uk', 'Judicaël', 'Legal Assistant', 100);
