USE online_shop;

insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (2, 2, 5, 'How can I assist you today?', '2024-12-11');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (3, 3, 2, 'Thank you for shopping with us!', '2024-12-12');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (4, 4, 6, 'Is there anything else you need?', '2024-12-13');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (5, 5, 3, 'We appreciate your feedback.', '2024-12-14');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (6, 6, 7, 'Welcome back! Great to see you.', '2024-12-15');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (7, 7, 4, 'Your order has been processed.', '2024-12-16');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (8, 8, 8, 'Would you like to see more options?', '2024-12-17');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (9, 9, 9, 'Feel free to reach out anytime.', '2024-12-18');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (10, 10, 10, 'Hope you found everything okay.', '2024-12-19');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (11, 1, 11, 'Can I help you find something?', '2024-12-20');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (12, 2, 12, 'Thank you for visiting.', '2024-12-21');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (13, 3, 13, 'Would you like a bag?', '2024-12-22');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (14, 4, 14, 'Your satisfaction matters to us.', '2024-12-23');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (15, 5, 15, 'Enjoy your purchase!', '2024-12-24');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (16, 6, 16, 'Can I interest you in our new arrivals?', '2024-12-25');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (17, 7, 17, 'We offer free returns within 30 days.', '2024-12-26');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (18, 8, 18, 'Check out our sale section!', '2024-12-27');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (19, 9, 19, 'Thanks for being a loyal customer.', '2024-12-28');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (20, 10, 20, 'Need help with sizes?', '2024-12-29');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (21, 1, 21, 'Our new collection just dropped!', '2024-12-30');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (22, 2, 22, 'Would you like a gift receipt?', '2024-12-31');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (23, 3, 23, 'Have a wonderful day!', '2025-01-01');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (24, 4, 24, 'Sign up for rewards program!', '2025-01-02');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (25, 5, 25, 'Thanks for visiting us.', '2025-01-03');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (26, 6, 26, 'Would you like a coffee while you shop?', '2025-01-04');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (27, 7, 27, 'Check out these customer favorites.', '2025-01-05');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (28, 8, 28, 'Would you like me to hold that for you?', '2025-01-06');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (29, 9, 29, 'Take your time, no rush.', '2025-01-07');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (30, 10, 30, 'Let me know if you need a fitting room.', '2025-01-08');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (31, 1, 31, 'Our store is having a special event!', '2025-01-09');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (32, 2, 32, 'Would you like to sign up for our newsletter?', '2025-01-10');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (33, 3, 33, 'Can I help you with anything else?', '2025-01-11');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (34, 4, 34, 'We have an exclusive discount for today!', '2025-01-12');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (35, 5, 35, 'Would you like to add a matching accessory?', '2025-01-13');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (36, 6, 36, 'Check out our new arrivals for the season!', '2025-01-14');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (37, 7, 37, 'Are you shopping for anything special?', '2025-01-15');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (38, 8, 38, 'Would you like me to wrap that up for you?', '2025-01-16');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (39, 9, 39, 'Let me know if you need any help with sizes.', '2025-01-17');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (40, 10, 40, 'Looking for something specific today?', '2025-01-18');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (41, 1, 41, 'We have some great deals in our clearance section!', '2025-01-19');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (42, 2, 42, 'Would you like to join our rewards program?', '2025-01-20');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (43, 3, 43, 'How was your shopping experience today?', '2025-01-21');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (44, 4, 44, 'We’re here to make your shopping easier!', '2025-01-22');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (45, 5, 45, 'Do you need help finding the right size?', '2025-01-23');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (46, 6, 46, 'Check out our customer favorites for today!', '2025-01-24');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (47, 7, 47, 'Would you like to add a gift note?', '2025-01-25');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (48, 8, 48, 'Let me know if you need help.', '2025-01-26');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (49, 9, 49, 'Can I offer you a discount today?', '2025-01-27');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (50, 10, 50, 'Don’t forget to check online!', '2025-01-28');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (51, 1, 51, 'We have a new collection for winter!', '2025-01-29');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (52, 2, 52, 'Thanks for shopping with us today!', '2025-01-30');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (151, 1, 53, 'We have a new collection of summer wear!', '2025-05-10');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (152, 2, 54, 'Would you like a personal shopping assistant?', '2025-05-11');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (153, 3, 55, 'Have you checked out our loyalty program?', '2025-05-12');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (154, 4, 56, 'We have great options for gifting!', '2025-05-13');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (155, 5, 57, 'Check out our latest accessories collection!', '2025-05-14');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (156, 6, 58, 'Looking for something specific?', '2025-05-15');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (157, 7, 59, 'Let me know if you need sizes!', '2025-05-16');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (158, 8, 60, 'We offer personalized styling.', '2025-05-17');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (159, 9, 61, 'Are you shopping for any occasion?', '2025-05-18');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (160, 10, 62, 'Don’t forget about our sales event!', '2025-05-19');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (161, 1, 63, 'Would you like to check out our items?', '2025-05-20');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (162, 2, 64, 'We have a discount for first-time customers!', '2025-05-21');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (163, 3, 65, 'We just got a new shipment of trendy items!', '2025-05-22');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (164, 4, 66, 'We have a great selection of handbags on sale!', '2025-05-23');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (165, 5, 67, 'We’ve got you covered!', '2025-05-24');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (166, 6, 68, 'Would you like to see our latest?', '2025-05-25');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (167, 7, 69, 'We have an exclusive offer for customers.', '2025-05-26');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (168, 8, 70, 'Let me know if you need assistance.', '2025-05-27');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (169, 9, 71, 'Our store just got a new range!', '2025-05-28');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (170, 10, 72, 'Would you like to check out?', '2025-05-29');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (171, 1, 73, 'We’re offering free delivery!', '2025-05-30');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (172, 2, 74, 'Our sale on outerwear ends tomorrow.', '2025-05-31');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (173, 3, 75, 'Looking for something more eco-friendly?', '2025-06-01');
