USE online_shop;

insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('99402', 1, 'leather skirt', 'bottoms', '20.00', 'leather', 10, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('442', 2, 'navy-blue jeans', 'bottoms', '50.00', 'denim', 10, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('145', 3, 'black jeans', 'bottoms', '60.00', 'denim', 6, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('25', 4, 'white crop top', 'tops', '16.00', 'cotton', 7, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('91', 5, 'black crop top', 'tops', '16.00', 'cotton', 1, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('45125', 6, 'bracelet', 'accessories', '5.00', 'brass', 1, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('6', 7, 'red hat', 'accessories', '7.00', 'polyester', 2, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('8', 8, 'black hat', 'accessories', '7.00', 'polyester', 7, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('271', 9, 'red crop top', 'tops', '16.00', 'cotton', 1, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('78386', 10, 'blue sequin blouse', 'blouses', '20.00', 'polyester', 3, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('52', 11, 'gold hoop earrings', 'accessories', '7.00', 'metal', 2, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('96724', 12, 'white cardigan', 'sweaters', '10.00', 'cotton', 9, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('4', 13, 'blue sweater', 'sweaters', '22.00', 'wool', 10, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('0477', 14, 'white sweater', 'sweaters', '22.00', 'wool', 8, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10002', 26, 'white graphic tee', 'tops', '20.00', 'cotton', 8, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10003', 27, 'grey sweatpants', 'bottoms', '30.00', 'cotton', 7, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10004', 28, 'red wrap dress', 'dresses', '55.00', 'polyester', 6, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10005', 29, 'tan loafers', 'shoes', '75.00', 'leather', 5, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10006', 30, 'light blue ripped jeans', 'bottoms', '60.00', 'denim', 8, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10007', 31, 'yellow sundress', 'dresses', '40.00', 'linen', 9, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10008', 32, 'black leggings', 'bottoms', '25.00', 'spandex', 10, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10009', 33, 'white sneakers', 'shoes', '90.00', 'canvas', 9, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10010', 34, 'pink satin blouse', 'blouses', '35.00', 'satin', 6, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10011', 35, 'olive bomber jacket', 'outerwear', '95.00', 'polyester', 8, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10012', 36, 'floral midi skirt', 'bottoms', '45.00', 'cotton', 7, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10013', 37, 'navy blue trench coat', 'outerwear', '150.00', 'cotton', 10, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10014', 38, 'khaki shorts', 'bottoms', '25.00', 'cotton', 5, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10015', 39, 'plaid mini skirt', 'bottoms', '30.00', 'wool', 8, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10016', 40, 'black turtleneck sweater', 'sweaters', '45.00', 'wool', 10, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10017', 41, 'orange knit beanie', 'accessories', '15.00', 'wool', 6, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10018', 42, 'faux fur vest', 'outerwear', '85.00', 'polyester', 7, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10019', 43, 'cropped denim jacket', 'outerwear', '70.00', 'denim', 9, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10020', 44, 'beige cargo pants', 'bottoms', '40.00', 'cotton', 7, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10021', 45, 'white canvas backpack', 'accessories', '50.00', 'canvas', 5, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10022', 46, 'grey puffer jacket', 'outerwear', '120.00', 'polyester', 8, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10023', 47, 'navy joggers', 'bottoms', '35.00', 'cotton', 7, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10024', 48, 'white V-neck sweater', 'sweaters', '48.00', 'cotton', 8, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10025', 49, 'brown leather belt', 'accessories', '30.00', 'leather', 6, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10026', 50, 'black platform boots', 'shoes', '95.00', 'leather', 9, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10027', 51, 'beige button-up shirt', 'tops', '38.00', 'linen', 8, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10028', 52, 'red velvet dress', 'dresses', '85.00', 'velvet', 7, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10029', 53, 'black skinny jeans', 'bottoms', '55.00', 'denim', 10, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10030', 54, 'lavender hoodie', 'sweaters', '42.00', 'cotton', 6, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10031', 55, 'grey cashmere scarf', 'accessories', '70.00', 'cashmere', 7, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10032', 56, 'denim overalls', 'bottoms', '65.00', 'denim', 8, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10033', 57, 'olive green parka', 'outerwear', '140.00', 'polyester', 9, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10034', 58, 'striped pencil skirt', 'bottoms', '36.00', 'cotton', 7, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10035', 59, 'silver charm bracelet', 'accessories', '20.00', 'metal', 5, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10036', 60, 'rose gold watch', 'accessories', '150.00', 'metal', 9, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10037', 61, 'coral tank top', 'tops', '18.00', 'cotton', 6, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10038', 62, 'pink fuzzy slippers', 'shoes', '25.00', 'polyester', 5, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10039', 63, 'cream knit cardigan', 'sweaters', '52.00', 'wool', 9, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10040', 64, 'camo cargo shorts', 'bottoms', '28.00', 'cotton', 6, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10041', 65, 'lightwash mom jeans', 'bottoms', '62.00', 'denim', 8, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10042', 66, 'white midi dress', 'dresses', '65.00', 'cotton', 7, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10043', 67, 'black loafer heels', 'shoes', '85.00', 'leather', 8, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10044', 68, 'navy cardigan', 'sweaters', '48.00', 'cotton', 6, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10045', 69, 'leather wallet', 'accessories', '45.00', 'leather', 7, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10046', 70, 'black athletic shorts', 'bottoms', '25.00', 'spandex', 9, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10047', 71, 'yellow puffer vest', 'outerwear', '95.00', 'polyester', 8, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10048', 72, 'black leather boots', 'shoes', '140.00', 'leather', 10, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10049', 73, 'striped long-sleeve shirt', 'tops', '32.00', 'cotton', 7, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10050', 74, 'burgundy velvet blazer', 'outerwear', '110.00', 'velvet', 8, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10051', 75, 'green pleated skirt', 'bottoms', '38.00', 'polyester', 6, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10052', 76, 'black drawstring backpack', 'accessories', '45.00', 'nylon', 7, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10053', 77, 'white ripped shorts', 'bottoms', '30.00', 'denim', 8, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10054', 78, 'gray trench coat', 'outerwear', '130.00', 'cotton', 9, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10055', 79, 'silver pendant necklace', 'accessories', '25.00', 'metal', 5, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10056', 80, 'cream cable-knit sweater', 'sweaters', '55.00', 'wool', 10, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10057', 81, 'blue board shorts', 'bottoms', '28.00', 'polyester', 6, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10058', 82, 'brown hiking boots', 'shoes', '95.00', 'leather', 7, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10059', 83, 'yellow floral blouse', 'blouses', '35.00', 'cotton', 8, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10060', 84, 'pink athletic leggings', 'bottoms', '40.00', 'spandex', 9, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10061', 85, 'olive utility jacket', 'outerwear', '100.00', 'cotton', 7, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10062', 86, 'striped crop top', 'tops', '22.00', 'cotton', 8, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10063', 87, 'grey slip dress', 'dresses', '50.00', 'silk', 6, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10064', 88, 'navy blue chinos', 'bottoms', '55.00', 'cotton', 7, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10065', 89, 'black faux leather pants', 'bottoms', '70.00', 'faux leather', 8, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10066', 90, 'cream lace top', 'tops', '35.00', 'lace', 7, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10067', 91, 'white denim jacket', 'outerwear', '75.00', 'denim', 9, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10068', 92, 'green satin skirt', 'bottoms', '42.00', 'satin', 6, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10069', 93, 'black wool beanie', 'accessories', '20.00', 'wool', 8, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10070', 94, 'white espadrille flats', 'shoes', '65.00', 'canvas', 7, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10071', 95, 'beige utility pants', 'bottoms', '48.00', 'cotton', 6, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10072', 96, 'blue chambray shirt', 'tops', '38.00', 'chambray', 7, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10073', 97, 'red checkered scarf', 'accessories', '22.00', 'wool', 6, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10074', 98, 'black tulle skirt', 'bottoms', '45.00', 'tulle', 8, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10075', 99, 'navy cargo jacket', 'outerwear', '105.00', 'cotton', 9, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10076', 100, 'green ribbed sweater', 'sweaters', '58.00', 'cotton', 7, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10077', 1, 'white ruffle blouse', 'blouses', '40.00', 'cotton', 6, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10078', 2, 'blue polka dot dress', 'dresses', '68.00', 'polyester', 8, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10079', 3, 'brown suede boots', 'shoes', '120.00', 'suede', 9, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10080', 4, 'pink denim skirt', 'bottoms', '40.00', 'denim', 7, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10081', 5, 'grey sports bra', 'tops', '28.00', 'spandex', 9, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10082', 6, 'black ripped skinny jeans', 'bottoms', '60.00', 'denim', 10, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10083', 7, 'green wide-leg pants', 'bottoms', '55.00', 'cotton', 7, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10084', 8, 'yellow cable-knit beanie', 'accessories', '18.00', 'wool', 6, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10085', 9, 'white boyfriend jeans', 'bottoms', '65.00', 'denim', 8, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10086', 10, 'navy plaid coat', 'outerwear', '150.00', 'wool', 9, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10087', 11, 'pink faux fur coat', 'outerwear', '160.00', 'faux fur', 7, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10088', 12, 'grey oversized hoodie', 'sweaters', '50.00', 'cotton', 10, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10089', 13, 'black leather sandals', 'shoes', '75.00', 'leather', 8, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10090', 14, 'white knit gloves', 'accessories', '22.00', 'wool', 5, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10091', 15, 'cream wide-brim hat', 'accessories', '35.00', 'wool', 7, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10092', 16, 'red plaid scarf', 'accessories', '20.00', 'wool', 6, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10093', 17, 'blue graphic hoodie', 'sweaters', '48.00', 'cotton', 9, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10094', 18, 'orange bomber jacket', 'outerwear', '110.00', 'polyester', 8, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10095', 19, 'pink sequin dress', 'dresses', '90.00', 'polyester', 7, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10096', 20, 'black leather mini skirt', 'bottoms', '65.00', 'leather', 9, false);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10097', 21, 'green floral romper', 'dresses', '58.00', 'cotton', 8, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10098', 22, 'navy slim-fit blazer', 'outerwear', '130.00', 'wool', 9, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10099', 23, 'white tennis skirt', 'bottoms', '45.00', 'cotton', 10, true);
insert into Product (SKU, brandID, name, category, price, material, trendScore, eco_certification) values ('10100', 24, 'grey herringbone coat', 'outerwear', '145.00', 'wool', 9, true);
