USE online_shop;

insert into ProductFeatures (SKU, feature) values ('10002', 'handmade');
insert into ProductFeatures (SKU, feature) values ('10003', 'stretchable');
insert into ProductFeatures (SKU, feature) values ('10004', 'breathable');
insert into ProductFeatures (SKU, feature) values ('10005', 'UV-resistant');
insert into ProductFeatures (SKU, feature) values ('10006', 'wrinkle-free');
insert into ProductFeatures (SKU, feature) values ('10007', 'stain-resistant');
insert into ProductFeatures (SKU, feature) values ('10008', 'recycled materials');
insert into ProductFeatures (SKU, feature) values ('10009', 'lightweight');
insert into ProductFeatures (SKU, feature) values ('10010', 'moisture-wicking');
insert into ProductFeatures (SKU, feature) values ('10011', 'vegan');
insert into ProductFeatures (SKU, feature) values ('10012', 'quick-dry');
insert into ProductFeatures (SKU, feature) values ('10013', 'odor-resistant');
insert into ProductFeatures (SKU, feature) values ('10014', 'insulated');
insert into ProductFeatures (SKU, feature) values ('10015', 'hypoallergenic');
insert into ProductFeatures (SKU, feature) values ('10016', 'adjustable fit');
insert into ProductFeatures (SKU, feature) values ('10017', 'machine-washable');
insert into ProductFeatures (SKU, feature) values ('10018', 'padded');
insert into ProductFeatures (SKU, feature) values ('10019', 'detachable hood');
insert into ProductFeatures (SKU, feature) values ('10020', 'thermal-regulating');
insert into ProductFeatures (SKU, feature) values ('10021', 'eco-friendly dyes');
insert into ProductFeatures (SKU, feature) values ('10022', 'fade-resistant');
insert into ProductFeatures (SKU, feature) values ('10023', 'high-visibility');
insert into ProductFeatures (SKU, feature) values ('10024', 'stretch waistband');
insert into ProductFeatures (SKU, feature) values ('10025', 'packable');
insert into ProductFeatures (SKU, feature) values ('10026', 'convertible');
insert into ProductFeatures (SKU, feature) values ('10027', 'reinforced seams');
insert into ProductFeatures (SKU, feature) values ('10028', 'thermal insulation');
insert into ProductFeatures (SKU, feature) values ('10029', 'anti-bacterial');
insert into ProductFeatures (SKU, feature) values ('10030', 'soft-touch');
insert into ProductFeatures (SKU, feature) values ('10031', 'reflective details');
insert into ProductFeatures (SKU, feature) values ('10032', 'abrasion-resistant');
insert into ProductFeatures (SKU, feature) values ('10033', 'odor control');
insert into ProductFeatures (SKU, feature) values ('10034', 'wrinkle-resistant');
insert into ProductFeatures (SKU, feature) values ('10035', 'thermal lined');
insert into ProductFeatures (SKU, feature) values ('10036', 'wind-resistant');
insert into ProductFeatures (SKU, feature) values ('10037', 'sweatproof');
insert into ProductFeatures (SKU, feature) values ('10038', 'reversible');
insert into ProductFeatures (SKU, feature) values ('10039', 'biodegradable');
insert into ProductFeatures (SKU, feature) values ('10040', 'scratch-resistant');
insert into ProductFeatures (SKU, feature) values ('10041', 'fade-proof');
insert into ProductFeatures (SKU, feature) values ('10042', 'cooling technology');
insert into ProductFeatures (SKU, feature) values ('10043', 'soft lining');
insert into ProductFeatures (SKU, feature) values ('10044', 'non-slip');
insert into ProductFeatures (SKU, feature) values ('10045', 'shock-absorbing');
insert into ProductFeatures (SKU, feature) values ('10046', 'ventilated');
insert into ProductFeatures (SKU, feature) values ('10047', 'featherweight');
insert into ProductFeatures (SKU, feature) values ('10048', 'multi-pocket');
insert into ProductFeatures (SKU, feature) values ('10049', 'ultra-soft');
insert into ProductFeatures (SKU, feature) values ('10050', 'zippered pockets');
insert into ProductFeatures (SKU, feature) values ('10051', 'double-stitched');
insert into ProductFeatures (SKU, feature) values ('10052', 'air-permeable');
insert into ProductFeatures (SKU, feature) values ('10053', 'elastic cuffs');
insert into ProductFeatures (SKU, feature) values ('10054', 'inner fleece');
insert into ProductFeatures (SKU, feature) values ('10055', 'durable water-repellent');
insert into ProductFeatures (SKU, feature) values ('10056', 'removable sleeves');
insert into ProductFeatures (SKU, feature) values ('10057', 'snag-resistant');
insert into ProductFeatures (SKU, feature) values ('10058', 'low impact production');
insert into ProductFeatures (SKU, feature) values ('10059', 'easy care');
insert into ProductFeatures (SKU, feature) values ('10060', 'slim fit');
insert into ProductFeatures (SKU, feature) values ('10061', 'classic fit');
insert into ProductFeatures (SKU, feature) values ('10062', 'loose fit');
insert into ProductFeatures (SKU, feature) values ('10063', 'seamless design');
insert into ProductFeatures (SKU, feature) values ('10064', 'tagless');
insert into ProductFeatures (SKU, feature) values ('10065', 'double-layered');
insert into ProductFeatures (SKU, feature) values ('10066', 'high-rise');
insert into ProductFeatures (SKU, feature) values ('10067', 'mid-rise');
insert into ProductFeatures (SKU, feature) values ('10068', 'low-rise');
insert into ProductFeatures (SKU, feature) values ('10069', 'wide-leg');
insert into ProductFeatures (SKU, feature) values ('10070', 'tapered');
insert into ProductFeatures (SKU, feature) values ('10071', 'bootcut');
insert into ProductFeatures (SKU, feature) values ('10072', 'water-resistant zippers');
insert into ProductFeatures (SKU, feature) values ('10073', 'ribbed cuffs');
insert into ProductFeatures (SKU, feature) values ('10074', 'high compression');
insert into ProductFeatures (SKU, feature) values ('10075', 'low compression');
insert into ProductFeatures (SKU, feature) values ('10076', 'eco-insulation');
insert into ProductFeatures (SKU, feature) values ('10077', 'breathable mesh');
insert into ProductFeatures (SKU, feature) values ('10078', 'mesh panels');
insert into ProductFeatures (SKU, feature) values ('10079', 'water-repellent fabric');
insert into ProductFeatures (SKU, feature) values ('10080', 'sustainable cotton');
insert into ProductFeatures (SKU, feature) values ('10081', 'plant-based fibers');
insert into ProductFeatures (SKU, feature) values ('10082', 'heat-sealed seams');
insert into ProductFeatures (SKU, feature) values ('10083', 'magnetic closures');
insert into ProductFeatures (SKU, feature) values ('10084', 'adjustable straps');
insert into ProductFeatures (SKU, feature) values ('10085', 'snap buttons');
insert into ProductFeatures (SKU, feature) values ('10086', 'removable liners');
insert into ProductFeatures (SKU, feature) values ('10087', 'insulated padding');
insert into ProductFeatures (SKU, feature) values ('10088', 'shrink-resistant');
insert into ProductFeatures (SKU, feature) values ('10089', 'thermoregulation');
insert into ProductFeatures (SKU, feature) values ('10090', 'ultra-breathable');
insert into ProductFeatures (SKU, feature) values ('10091', 'colorfast');
insert into ProductFeatures (SKU, feature) values ('10092', 'eco-certified');
insert into ProductFeatures (SKU, feature) values ('10093', 'anti-odor');
insert into ProductFeatures (SKU, feature) values ('10094', 'light-insulating');
insert into ProductFeatures (SKU, feature) values ('10095', 'smooth texture');
insert into ProductFeatures (SKU, feature) values ('10096', 'carbon-neutral');
insert into ProductFeatures (SKU, feature) values ('10097', 'upcycled fibers');
insert into ProductFeatures (SKU, feature) values ('10098', 'natural dyes');
insert into ProductFeatures (SKU, feature) values ('10099', 'non-toxic materials');
insert into ProductFeatures (SKU, feature) values ('10100', 'multi-season wear');