USE online_shop;

INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (1, 1, '10002', 'Cute clothes!', 2, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (2, 2, '10003', 'Loved it!', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (3, 3, '10004', 'Very comfortable', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (4, 4, '10005', 'Not bad', 3, 6);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (5, 5, '10006', 'Excellent product', 5, 10);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (6, 6, '10007', 'Pretty good!', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (7, 7, '10008', 'Great fit', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (8, 8, '10009', 'Decent', 3, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (9, 9, '10010', 'Comfortable', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (10, 10, '10011', 'Stylish', 4, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (11, 11, '10012', 'Not great', 2, 6);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (12, 12, '10013', 'Love it', 5, 10);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (13, 13, '10014', 'Not comfortable', 2, 5);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (14, 14, '10015', 'Fantastic!', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (15, 15, '10016', 'Nice quality', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (16, 16, '10017', 'Good product', 4, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (17, 17, '10018', 'Too tight', 3, 5);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (18, 18, '10019', 'Exactly as expected', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (19, 19, '10020', 'Poor fit', 2, 4);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (20, 20, '10021', 'Comfortable shoes', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (21, 21, '10022', 'Too loose', 3, 6);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (22, 22, '10023', 'Love them', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (23, 23, '10024', 'Not soft', 2, 5);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (24, 24, '10025', 'Perfect fit', 5, 10);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (25, 25, '10026', 'Good value', 4, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (26, 26, '10027', 'Love them!', 5, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (27, 27, '10028', 'Too small', 2, 5);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (28, 28, '10029', 'Really cute', 4, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (29, 29, '10030', 'Highly recommend', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (30, 30, '10031', 'Very soft', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (31, 31, '10032', 'Just okay', 3, 6);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (32, 32, '10033', 'Not comfortable', 2, 4);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (33, 33, '10034', 'Perfect!', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (34, 34, '10035', 'Pretty good', 4, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (35, 35, '10036', 'Love it!', 5, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (36, 36, '10037', 'Comfortable shoes', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (37, 37, '10038', 'Just perfect', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (38, 38, '10039', 'Very stylish', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (39, 39, '10040', 'Nice fit', 4, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (40, 40, '10041', 'Really good', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (41, 41, '10042', 'Just fine', 3, 6);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (42, 42, '10043', 'Not great', 2, 5);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (43, 43, '10044', 'Love these!', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (44, 44, '10045', 'Very comfortable', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (45, 45, '10046', 'Too big', 3, 6);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (46, 46, '10047', 'Fit well', 4, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (47, 47, '10048', 'Comfortable', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (48, 48, '10049', 'Not great', 2, 5);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (49, 49, '10050', 'Good product', 4, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (50, 50, '10051', 'Nice item', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (51, 51, '10052', 'Great quality!', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (52, 52, '10053', 'Not my style', 2, 4);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (53, 53, '10054', 'Love them!', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (54, 54, '10055', 'Very comfy', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (55, 55, '10056', 'Awesome item', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (56, 56, '10057', 'Too large', 3, 6);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (57, 57, '10058', 'Great fit', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (58, 58, '10059', 'Not comfy', 2, 4);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (59, 59, '10060', 'Perfect fit', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (60, 60, '10061', 'Not good', 2, 5);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (61, 61, '10062', 'Really soft', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (62, 62, '10063', 'Too tight', 3, 6);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (63, 63, '10064', 'Love this!', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (64, 64, '10065', 'Excellent product', 5, 10);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (65, 65, '10066', 'Comfy shoes', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (66, 66, '10067', 'Love them', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (67, 67, '10068', 'Nice!', 4, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (68, 68, '10069', 'Just right', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (69, 69, '10070', 'Too small', 3, 6);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (70, 70, '10071', 'Nice fit', 4, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (71, 71, '10072', 'Perfect!', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (72, 72, '10073', 'Decent', 3, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (73, 73, '10074', 'Great item', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (74, 74, '10075', 'Could be better', 2, 5);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (75, 75, '10076', 'Fits well', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (76, 76, '10077', 'Love them!', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (77, 77, '10078', 'Not my favorite', 3, 6);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (78, 78, '10079', 'Good fit', 4, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (79, 79, '10080', 'Nice shoes', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (80, 80, '10081', 'Love the look', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (81, 81, '10082', 'Good item', 4, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (82, 82, '10083', 'Not comfy', 2, 5);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (83, 83, '10084', 'Fantastic!', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (84, 84, '10085', 'Not impressed', 3, 6);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (85, 85, '10086', 'Fits fine', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (86, 86, '10087', 'Great!', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (87, 87, '10088', 'Not good', 2, 5);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (88, 88, '10089', 'Good shoes', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (89, 89, '10090', 'Very comfy', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (90, 90, '10091', 'Love it!', 5, 9);