USE db;


INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (1, 1, '432', 'Cute clothes!', 2, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (2, 2, '543', 'Loved it!', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (3, 3, '654', 'Very comfortable', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (4, 4, '765', 'Not bad', 3, 6);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (5, 5, '876', 'Excellent product', 5, 10);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (6, 6, '987', 'Pretty good!', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (7, 7, '123', 'Great fit', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (8, 8, '234', 'Decent', 3, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (9, 9, '345', 'Comfortable', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (10, 10, '456', 'Stylish', 4, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (11, 11, '567', 'Not great', 2, 6);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (12, 12, '678', 'Love it', 5, 10);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (13, 13, '789', 'Not comfortable', 2, 5);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (14, 14, '890', 'Fantastic!', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (15, 15, '901', 'Nice quality', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (16, 16, '012', 'Good product', 4, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (17, 17, '123', 'Too tight', 3, 5);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (18, 18, '234', 'Exactly as expected', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (19, 19, '345', 'Poor fit', 2, 4);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (20, 20, '456', 'Comfortable shoes', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (21, 21, '567', 'Too loose', 3, 6);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (22, 22, '678', 'Love them', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (23, 23, '789', 'Not soft', 2, 5);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (24, 24, '890', 'Perfect fit', 5, 10);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (25, 25, '901', 'Good value', 4, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (26, 26, '012', 'Love them!', 5, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (27, 27, '123', 'Too small', 2, 5);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (28, 28, '234', 'Really cute', 4, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (29, 29, '345', 'Highly recommend', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (30, 30, '456', 'Very soft', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (31, 31, '567', 'Just okay', 3, 6);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (32, 32, '678', 'Not comfortable', 2, 4);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (33, 33, '789', 'Perfect!', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (34, 34, '890', 'Pretty good', 4, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (35, 35, '901', 'Love it!', 5, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (36, 36, '012', 'Comfortable shoes', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (37, 37, '123', 'Just perfect', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (38, 38, '234', 'Very stylish', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (39, 39, '345', 'Nice fit', 4, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (40, 40, '456', 'Really good', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (41, 41, '567', 'Just fine', 3, 6);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (42, 42, '678', 'Not great', 2, 5);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (43, 43, '789', 'Love these!', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (44, 44, '890', 'Very comfortable', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (45, 45, '901', 'Too big', 3, 6);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (46, 46, '012', 'Fit well', 4, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (47, 47, '123', 'Comfortable', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (48, 48, '234', 'Not great', 2, 5);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (49, 49, '345', 'Good product', 4, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (50, 50, '456', 'Nice item', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (51, 51, '567', 'Great quality!', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (52, 52, '678', 'Not my style', 2, 4);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (53, 53, '789', 'Love them!', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (54, 54, '890', 'Very comfy', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (55, 55, '901', 'Awesome item', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (56, 56, '012', 'Too large', 3, 6);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (57, 57, '123', 'Great fit', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (58, 58, '234', 'Not comfy', 2, 4);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (59, 59, '345', 'Perfect fit', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (60, 60, '456', 'Not good', 2, 5);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (61, 61, '567', 'Really soft', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (62, 62, '678', 'Too tight', 3, 6);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (63, 63, '789', 'Love this!', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (64, 64, '890', 'Excellent product', 5, 10);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (65, 65, '901', 'Comfy shoes', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (66, 66, '012', 'Love them', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (67, 67, '123', 'Nice!', 4, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (68, 68, '234', 'Just right', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (69, 69, '345', 'Too small', 3, 6);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (70, 70, '456', 'Nice fit', 4, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (71, 71, '567', 'Perfect!', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (72, 72, '678', 'Decent', 3, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (73, 73, '789', 'Great item', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (74, 74, '890', 'Could be better', 2, 5);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (75, 75, '901', 'Fits well', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (76, 76, '012', 'Love them!', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (77, 77, '123', 'Not my favorite', 3, 6);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (78, 78, '234', 'Good fit', 4, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (79, 79, '345', 'Nice shoes', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (80, 80, '456', 'Love the look', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (81, 81, '567', 'Good item', 4, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (82, 82, '678', 'Not comfy', 2, 5);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (83, 83, '789', 'Fantastic!', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (84, 84, '890', 'Not impressed', 3, 6);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (85, 85, '901', 'Fits fine', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (86, 86, '012', 'Great!', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (87, 87, '123', 'Not good', 2, 5);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (88, 88, '234', 'Good shoes', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (89, 89, '345', 'Very comfy', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (90, 90, '456', 'Love it!', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (91, 91, '567', 'Perfect fit', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (92, 92, '678', 'Love them', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (93, 93, '789', 'Really nice', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (94, 94, '890', 'Decent shoes', 3, 7);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (95, 95, '901', 'Okay product', 3, 6);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (96, 96, '012', 'Not great', 2, 5);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (97, 97, '123', 'Good shoes', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (98, 98, '234', 'Comfortable', 4, 8);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (99, 99, '345', 'Fit perfect', 5, 9);
INSERT INTO Review (reviewID, customerID, SKU, comment, rating, comfort_score) VALUES (100, 100, '456', 'Too tight', 2, 5);
