USE online_shop;


insert into Store (store_id, name, isOnline, location) values (1, 'VonRueden Group', true, '541 Columbia Court');
insert into Store (store_id, name, isOnline, location) values (2, 'Smith & Sons', false, '123 Oak Street');
insert into Store (store_id, name, isOnline, location) values (3, 'Johnson Apparel', true, '654 Pine Avenue');
insert into Store (store_id, name, isOnline, location) values (4, 'Miller Fashion', true, '987 Elm Road');
insert into Store (store_id, name, isOnline, location) values (5, 'Taylor & Co.', false, '213 Maple Drive');
insert into Store (store_id, name, isOnline, location) values (6, 'GreenLeaf Clothing', true, '321 Birch Boulevard');
insert into Store (store_id, name, isOnline, location) values (7, 'Davis Fashion House', false, '765 Cedar Lane');
insert into Store (store_id, name, isOnline, location) values (8, 'Wilson & Co.', true, '432 Spruce Avenue');
insert into Store (store_id, name, isOnline, location) values (9, 'Peterson Styles', true, '876 Walnut Street');
insert into Store (store_id, name, isOnline, location) values (10, 'Harris Designs', false, '199 Oakdale Road');
insert into Store (store_id, name, isOnline, location) values (11, 'Nelson Clothing', true, '234 Pinehurst Drive');
insert into Store (store_id, name, isOnline, location) values (12, 'Walker Fashion', false, '987 Oakwood Lane');
insert into Store (store_id, name, isOnline, location) values (13, 'Collins Couture', true, '612 Willow Street');
insert into Store (store_id, name, isOnline, location) values (14, 'Simmons & Partners', true, '785 Birchwood Avenue');
insert into Store (store_id, name, isOnline, location) values (15, 'Evans & Sons', false, '543 Maple Road');
insert into Store (store_id, name, isOnline, location) values (16, 'Adams Apparel', true, '315 Pine Street');
insert into Store (store_id, name, isOnline, location) values (17, 'Murphy & Co.', false, '240 Cedar Avenue');
insert into Store (store_id, name, isOnline, location) values (18, 'Roberts Trends', true, '432 Elm Boulevard');
insert into Store (store_id, name, isOnline, location) values (19, 'Mitchell Designs', true, '654 Maple Drive');
insert into Store (store_id, name, isOnline, location) values (20, 'Baker Fashion', false, '871 Oak Lane');
insert into Store (store_id, name, isOnline, location) values (21, 'Martin Apparel', true, '123 Pinewood Drive');
insert into Store (store_id, name, isOnline, location) values (22, 'Lewis Couture', true, '654 Cedar Street');
insert into Store (store_id, name, isOnline, location) values (23, 'Gonzalez Style', false, '456 Oak Road');
insert into Store (store_id, name, isOnline, location) values (24, 'Robinson Designs', true, '789 Maple Street');
insert into Store (store_id, name, isOnline, location) values (25, 'Clark Clothing', false, '321 Elm Avenue');
insert into Store (store_id, name, isOnline, location) values (26, 'Lopez Trends', true, '654 Pine Boulevard');
insert into Store (store_id, name, isOnline, location) values (27, 'Perez Couture', false, '987 Cedar Road');
insert into Store (store_id, name, isOnline, location) values (28, 'Young & Co.', true, '543 Willow Lane');
insert into Store (store_id, name, isOnline, location) values (29, 'Walker Styles', true, '876 Birchwood Drive');
insert into Store (store_id, name, isOnline, location) values (30, 'King Fashion', false, '123 Oakwood Boulevard');
insert into Store (store_id, name, isOnline, location) values (31, 'Green Trends', true, '234 Cedar Drive');
insert into Store (store_id, name, isOnline, location) values (32, 'Hernandez Couture', true, '654 Maple Lane');
insert into Store (store_id, name, isOnline, location) values (33, 'Jackson & Sons', false, '543 Pine Avenue');
insert into Store (store_id, name, isOnline, location) values (34, 'Martinez Apparel', true, '765 Willow Street');
insert into Store (store_id, name, isOnline, location) values (35, 'Taylor Couture', false, '876 Oak Street');
insert into Store (store_id, name, isOnline, location) values (36, 'Moore Fashion', true, '432 Birch Lane');
insert into Store (store_id, name, isOnline, location) values (37, 'Brown Trends', true, '654 Spruce Drive');
insert into Store (store_id, name, isOnline, location) values (38, 'Wilson Couture', false, '123 Cedar Road');
insert into Store (store_id, name, isOnline, location) values (39, 'Lopez Apparel', true, '876 Oakwood Drive');
insert into Store (store_id, name, isOnline, location) values (40, 'Harris Couture', true, '234 Elm Lane');
insert into Store (store_id, name, isOnline, location) values (41, 'Collins Apparel', false, '543 Birch Boulevard');
insert into Store (store_id, name, isOnline, location) values (42, 'Martinez Trends', true, '765 Maple Boulevard');
insert into Store (store_id, name, isOnline, location) values (43, 'Clark Designs', false, '432 Pinewood Road');
insert into Store (store_id, name, isOnline, location) values (44, 'Reed Couture', true, '234 Oakwood Avenue');
insert into Store (store_id, name, isOnline, location) values (45, 'Roberts Couture', false, '876 Cedar Boulevard');
insert into Store (store_id, name, isOnline, location) values (46, 'Adams Designs', true, '543 Elm Drive');
insert into Store (store_id, name, isOnline, location) values (47, 'Lewis Apparel', true, '654 Birch Road');
insert into Store (store_id, name, isOnline, location) values (48, 'Nelson Couture', false, '321 Cedar Street');
insert into Store (store_id, name, isOnline, location) values (49, 'Gonzalez Fashion', true, '987 Pinewood Avenue');
insert into Store (store_id, name, isOnline, location) values (50, 'GreenLeaf Designs', true, '234 Willow Lane');
insert into Store (store_id, name, isOnline, location) values (51, 'Bennett Couture', true, '432 Oak Boulevard');
insert into Store (store_id, name, isOnline, location) values (52, 'Johnson Designs', false, '765 Birch Avenue');
insert into Store (store_id, name, isOnline, location) values (53, 'White Fashion', true, '654 Pine Road');
insert into Store (store_id, name, isOnline, location) values (54, 'Wright & Sons', false, '987 Maple Boulevard');
insert into Store (store_id, name, isOnline, location) values (55, 'Lee Couture', true, '543 Cedar Avenue');
insert into Store (store_id, name, isOnline, location) values (56, 'Hughes Apparel', true, '432 Elm Boulevard');
insert into Store (store_id, name, isOnline, location) values (57, 'Gomez & Co.', false, '765 Oakwood Avenue');
insert into Store (store_id, name, isOnline, location) values (58, 'Parker Fashion', true, '654 Birch Boulevard');
insert into Store (store_id, name, isOnline, location) values (59, 'Morris Couture', false, '876 Pine Drive');
insert into Store (store_id, name, isOnline, location) values (60, 'Mendez Designs', true, '234 Willow Street');
insert into Store (store_id, name, isOnline, location) values (61, 'Garcia Apparel', true, '543 Oak Lane');
insert into Store (store_id, name, isOnline, location) values (62, 'Dunn Couture', false, '765 Pinewood Boulevard');
insert into Store (store_id, name, isOnline, location) values (63, 'Scott Fashion', true, '876 Birchwood Road');
insert into Store (store_id, name, isOnline, location) values (64, 'Hawkins Couture', true, '432 Willow Boulevard');
insert into Store (store_id, name, isOnline, location) values (65, 'Mitchell & Co.', false, '321 Pine Boulevard');
insert into Store (store_id, name, isOnline, location) values (66, 'Fisher Apparel', true, '654 Maple Street');
insert into Store (store_id, name, isOnline, location) values (67, 'Mason Couture', true, '765 Elm Lane');
insert into Store (store_id, name, isOnline, location) values (68, 'Fowler Designs', false, '234 Birch Road');
insert into Store (store_id, name, isOnline, location) values (69, 'Reed Apparel', true, '543 Spruce Street');
insert into Store (store_id, name, isOnline, location) values (70, 'Turner Couture', true, '432 Maple Avenue');
insert into Store (store_id, name, isOnline, location) values (71, 'Bailey Fashion', false, '765 Oak Boulevard');
insert into Store (store_id, name, isOnline, location) values (72, 'Cameron Designs', true, '654 Pinewood Avenue');
insert into Store (store_id, name, isOnline, location) values (73, 'Morgan Couture', false, '987 Birchwood Street');
insert into Store (store_id, name, isOnline, location) values (74, 'Taylor Trends', true, '321 Elm Road');
insert into Store (store_id, name, isOnline, location) values (75, 'Martin Apparel', true, '432 Oakwood Boulevard');
insert into Store (store_id, name, isOnline, location) values (76, 'Simpson Couture', false, '765 Willow Lane');
insert into Store (store_id, name, isOnline, location) values (77, 'Graham Designs', true, '654 Cedar Boulevard');
insert into Store (store_id, name, isOnline, location) values (78, 'Evans Apparel', true, '234 Pine Lane');
insert into Store (store_id, name, isOnline, location) values (79, 'Grant Couture', false, '432 Birchwood Road');
insert into Store (store_id, name, isOnline, location) values (80, 'Barnes Fashion', true, '765 Maple Drive');
insert into Store (store_id, name, isOnline, location) values (81, 'Phillips Couture', true, '654 Oak Boulevard');
insert into Store (store_id, name, isOnline, location) values (82, 'Reyes Apparel', false, '321 Pinewood Drive');
insert into Store (store_id, name, isOnline, location) values (83, 'Diaz Fashion', true, '432 Elm Lane');
insert into Store (store_id, name, isOnline, location) values (84, 'Carson Couture', true, '543 Birchwood Boulevard');
insert into Store (store_id, name, isOnline, location) values (85, 'Wallace Apparel', false, '876 Maple Avenue');
insert into Store (store_id, name, isOnline, location) values (86, 'Roberts Trends', true, '765 Pine Lane');
insert into Store (store_id, name, isOnline, location) values (87, 'Fletcher Couture', false, '234 Cedar Boulevard');
insert into Store (store_id, name, isOnline, location) values (88, 'Stewart Apparel', true, '543 Oakwood Road');
insert into Store (store_id, name, isOnline, location) values (89, 'Dixon Couture', true, '654 Elm Avenue');
insert into Store (store_id, name, isOnline, location) values (90, 'Perez Trends', false, '432 Pine Street');
insert into Store (store_id, name, isOnline, location) values (91, 'Chavez Couture', true, '765 Birch Lane');
insert into Store (store_id, name, isOnline, location) values (92, 'Harrison Apparel', true, '654 Oakwood Street');
insert into Store (store_id, name, isOnline, location) values (93, 'Wells Designs', false, '987 Pinewood Lane');
insert into Store (store_id, name, isOnline, location) values (94, 'Kelly Fashion', true, '432 Cedar Road');
insert into Store (store_id, name, isOnline, location) values (95, 'Frazier Couture', true, '765 Elm Boulevard');
insert into Store (store_id, name, isOnline, location) values (96, 'Gordon Apparel', false, '234 Oakwood Boulevard');
insert into Store (store_id, name, isOnline, location) values (97, 'Bishop Couture', true, '543 Pinewood Lane');
insert into Store (store_id, name, isOnline, location) values (98, 'Henderson Designs', false, '654 Maple Road');
insert into Store (store_id, name, isOnline, location) values (99, 'Murray Couture', true, '765 Oak Avenue');
insert into Store (store_id, name, isOnline, location) values (100, 'Chapman Apparel', false, '432 Birchwood Lane');
