USE team4_online_shopping_database;
create table ManagerInteractions (
	interaction_id INT,
	manager_id INT,
	customer_id INT,
	message VARCHAR(50),
	date DATE
);
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (1, 1, 1, 'Let me know if you need help!', '2025-01-23');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (1, 1, 1, 'Let me know if you need help!', '2025-01-23');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (2, 2, 2, 'How can I assist you today?', '2025-01-24');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (3, 3, 3, 'Feel free to ask!', '2025-01-25');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (4, 4, 4, 'Let me know if you need anything.', '2025-01-26');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (5, 5, 5, 'How can I make your visit better?', '2025-01-27');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (6, 6, 6, 'Let me know your preferences!', '2025-01-28');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (7, 7, 7, 'Need assistance with anything?', '2025-01-29');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (8, 8, 8, 'I’m here to help you!', '2025-01-30');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (9, 9, 9, 'How can I be of service?', '2025-01-31');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (10, 10, 10, 'Feel free to reach out.', '2025-02-01');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (11, 1, 11, 'Can I assist you with something?', '2025-02-02');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (12, 2, 12, 'I’m happy to help if needed.', '2025-02-03');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (13, 3, 13, 'Here to help anytime!', '2025-02-04');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (14, 4, 14, 'Let me know how I can assist.', '2025-02-05');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (15, 5, 15, 'Anything else I can help with?', '2025-02-06');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (16, 6, 16, 'I’m happy to answer any questions!', '2025-02-07');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (17, 7, 17, 'Feel free to ask away!', '2025-02-08');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (18, 8, 18, 'I’m here if you need me.', '2025-02-09');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (19, 9, 19, 'Let me know if you need something.', '2025-02-10');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (20, 10, 20, 'Anything I can do for you?', '2025-02-11');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (21, 1, 21, 'How’s everything going?', '2025-02-12');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (22, 2, 22, 'Can I assist you with that?', '2025-02-13');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (23, 3, 23, 'Let me know if you have any questions.', '2025-02-14');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (24, 4, 24, 'Need help with anything today?', '2025-02-15');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (25, 5, 25, 'Here for any support you need.', '2025-02-16');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (26, 6, 26, 'Let me know if you need assistance.', '2025-02-17');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (27, 7, 27, 'Is there anything else I can help you with?', '2025-02-18');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (28, 8, 28, 'Can I help with something today?', '2025-02-19');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (29, 9, 29, 'How’s your experience so far?', '2025-02-20');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (30, 10, 30, 'I’m happy to assist!', '2025-02-21');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (31, 1, 31, 'How can I help you today?', '2025-02-22');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (32, 2, 32, 'Need any help with your order?', '2025-02-23');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (33, 3, 33, 'Happy to assist if needed.', '2025-02-24');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (34, 4, 34, 'Here if you need anything!', '2025-02-25');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (35, 5, 35, 'Feel free to ask for help.', '2025-02-26');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (36, 6, 36, 'I can help if you need it!', '2025-02-27');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (37, 7, 37, 'Let me know if I can assist.', '2025-02-28');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (38, 8, 38, 'I’m here for any questions.', '2025-03-01');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (39, 9, 39, 'Is there anything you need help with?', '2025-03-02');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (40, 10, 40, 'Let me know if you need advice.', '2025-03-03');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (41, 1, 41, 'Can I assist you with something?', '2025-03-04');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (42, 2, 42, 'Need anything today?', '2025-03-05');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (43, 3, 43, 'Let me know if you need help finding something.', '2025-03-06');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (44, 4, 44, 'Anything I can help with today?', '2025-03-07');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (45, 5, 45, 'Can I help with your shopping?', '2025-03-08');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (46, 6, 46, 'Anything you need assistance with?', '2025-03-09');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (47, 7, 47, 'I’m happy to assist you!', '2025-03-10');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (48, 8, 48, 'Need help finding your size?', '2025-03-11');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (49, 9, 49, 'I’m here if you need something!', '2025-03-12');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (50, 10, 50, 'Can I help you today?', '2025-03-13');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (51, 1, 51, 'Need assistance with your order?', '2025-03-14');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (52, 2, 52, 'Let me know if you need any help.', '2025-03-15');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (53, 3, 53, 'How can I assist you today?', '2025-03-16');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (54, 4, 54, 'I’m happy to help with anything.', '2025-03-17');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (55, 5, 55, 'Let me know if you need anything.', '2025-03-18');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (56, 6, 56, 'Can I assist you with something today?', '2025-03-19');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (57, 7, 57, 'Feel free to ask if you need help.', '2025-03-20');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (58, 8, 58, 'Here to help you if needed!', '2025-03-21');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (59, 9, 59, 'Let me know if you need assistance.', '2025-03-22');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (60, 10, 60, 'Can I help you with your selection?', '2025-03-23');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (61, 1, 61, 'How can I assist with your shopping?', '2025-03-24');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (62, 2, 62, 'Need help deciding?', '2025-03-25');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (63, 3, 63, 'Let me know if I can assist.', '2025-03-26');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (64, 4, 64, 'I’m here to help with anything.', '2025-03-27');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (65, 5, 65, 'Feel free to reach out for help.', '2025-03-28');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (66, 6, 66, 'I’m here if you need assistance.', '2025-03-29');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (67, 7, 67, 'Can I help with anything today?', '2025-03-30');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (68, 8, 68, 'Anything you need help with?', '2025-03-31');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (69, 9, 69, 'Let me know if I can assist you.', '2025-04-01');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (70, 10, 70, 'How can I be of service today?', '2025-04-02');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (71, 1, 71, 'Feel free to ask any questions!', '2025-04-03');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (72, 2, 72, 'Anything I can do for you today?', '2025-04-04');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (73, 3, 73, 'Let me know if you need help!', '2025-04-05');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (74, 4, 74, 'Can I help you find something?', '2025-04-06');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (75, 5, 75, 'Happy to assist with your needs.', '2025-04-07');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (76, 6, 76, 'Anything I can assist with today?', '2025-04-08');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (77, 7, 77, 'I’m happy to help you out.', '2025-04-09');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (78, 8, 78, 'Let me know if you need any help.', '2025-04-10');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (79, 9, 79, 'How can I make your experience better?', '2025-04-11');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (80, 10, 80, 'Let me know if I can be of assistance!', '2025-04-12');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (81, 1, 81, 'Can I assist you with your shopping?', '2025-04-13');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (82, 2, 82, 'Feel free to ask if you need anything.', '2025-04-14');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (83, 3, 83, 'How can I help you today?', '2025-04-15');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (84, 4, 84, 'Anything I can assist with today?', '2025-04-16');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (85, 5, 85, 'Let me know if you need something.', '2025-04-17');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (86, 6, 86, 'I’m happy to assist with anything.', '2025-04-18');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (87, 7, 87, 'Feel free to reach out anytime.', '2025-04-19');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (88, 8, 88, 'Let me know how I can help you.', '2025-04-20');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (89, 9, 89, 'How can I assist you today?', '2025-04-21');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (90, 10, 90, 'I’m happy to help anytime.', '2025-04-22');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (91, 1, 91, 'Can I assist with anything else?', '2025-04-23');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (92, 2, 92, 'Feel free to ask if needed!', '2025-04-24');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (93, 3, 93, 'Let me know if you need support.', '2025-04-25');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (94, 4, 94, 'Can I help with your selection today?', '2025-04-26');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (95, 5, 95, 'Here to help anytime!', '2025-04-27');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (96, 6, 96, 'Let me know if you need help finding something.', '2025-04-28');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (97, 7, 97, 'I’m happy to assist with any questions.', '2025-04-29');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (98, 8, 98, 'How can I help you today?', '2025-04-30');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (99, 9, 99, 'Let me know if you need any help!', '2025-05-01');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (100, 10, 100, 'Need help making a decision?', '2025-05-02');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (101, 1, 101, 'Can I assist with anything today?', '2025-05-03');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (102, 2, 102, 'Feel free to reach out for any help.', '2025-05-04');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (103, 3, 103, 'Let me know if you need support.', '2025-05-05');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (104, 4, 104, 'Anything you need assistance with today?', '2025-05-06');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (105, 5, 105, 'I’m here to help with anything you need.', '2025-05-07');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (106, 6, 106, 'Let me know if you need further assistance.', '2025-05-08');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (107, 7, 107, 'I’m happy to assist with any questions.', '2025-05-09');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (108, 8, 108, 'Feel free to ask if you need help.', '2025-05-10');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (109, 9, 109, 'How can I assist you today?', '2025-05-11');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (110, 10, 110, 'Can I help you with something?', '2025-05-12');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (111, 1, 111, 'Anything I can assist you with today?', '2025-05-13');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (112, 2, 112, 'Let me know if you need anything.', '2025-05-14');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (113, 3, 113, 'Feel free to ask if you need support.', '2025-05-15');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (114, 4, 114, 'Can I help with anything today?', '2025-05-16');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (115, 5, 115, 'Let me know if you need assistance.', '2025-05-17');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (116, 6, 116, 'I’m here to help you with anything.', '2025-05-18');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (117, 7, 117, 'Let me know how I can help you!', '2025-05-19');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (118, 8, 118, 'How can I assist you with your needs?', '2025-05-20');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (119, 9, 119, 'Can I help you with your selection?', '2025-05-21');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (120, 10, 120, 'Feel free to ask any questions.', '2025-05-22');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (121, 1, 121, 'Can I assist you with something today?', '2025-05-23');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (122, 2, 122, 'Let me know if you need help finding something.', '2025-05-24');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (123, 3, 123, 'Feel free to reach out if you need help.', '2025-05-25');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (124, 4, 124, 'How can I help you with your shopping?', '2025-05-26');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (125, 5, 125, 'I’m happy to assist with anything you need.', '2025-05-27');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (126, 6, 126, 'Anything you need assistance with?', '2025-05-28');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (127, 7, 127, 'Let me know if you need any support.', '2025-05-29');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (128, 8, 128, 'Can I help with your selection?', '2025-05-30');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (129, 9, 129, 'How can I assist with your shopping today?', '2025-05-31');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (130, 10, 130, 'Let me know if I can be of service today.', '2025-06-01');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (131, 1, 131, 'Let me know if you need anything!', '2025-06-02');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (132, 2, 132, 'Can I assist you with something?', '2025-06-03');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (133, 3, 133, 'Anything you need help with?', '2025-06-04');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (134, 4, 134, 'Let me know if you have any questions.', '2025-06-05');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (135, 5, 135, 'I’m happy to help anytime!', '2025-06-06');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (136, 6, 136, 'How can I assist you today?', '2025-06-07');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (137, 7, 137, 'Feel free to ask anything!', '2025-06-08');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (138, 8, 138, 'Can I assist with anything today?', '2025-06-09');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (139, 9, 139, 'Here to help with anything you need.', '2025-06-10');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (140, 10, 140, 'Let me know how I can help!', '2025-06-11');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (141, 1, 141, 'How can I help today?', '2025-06-12');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (142, 2, 142, 'I’m here if you need any assistance.', '2025-06-13');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (143, 3, 143, 'Let me know if you need support.', '2025-06-14');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (144, 4, 144, 'Can I help you with your shopping today?', '2025-06-15');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (145, 5, 145, 'Feel free to reach out anytime.', '2025-06-16');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (146, 6, 146, 'Here to help you find what you need.', '2025-06-17');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (147, 7, 147, 'Let me know if you need anything today.', '2025-06-18');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (148, 8, 148, 'Feel free to ask if you need help!', '2025-06-19');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (149, 9, 149, 'Anything I can help you with?', '2025-06-20');
insert into ManagerInteractions (interaction_id, manager_id, customer_id, message, date) values (150, 10, 150, 'Let me know if you need support today.', '2025-06-21');
