USE db;
create table ProductFeatures (
	SKU VARCHAR(50),
	feature VARCHAR(50)
);
insert into ProductFeatures (SKU, feature) values ('57', 'allergen-friendly');
insert into ProductFeatures (SKU, feature) values ('004', 'soft');
insert into ProductFeatures (SKU, feature) values ('6', 'waterproof');
insert into ProductFeatures (SKU, feature) values ('1001', 'organic');
insert into ProductFeatures (SKU, feature) values ('1002', 'handmade');
insert into ProductFeatures (SKU, feature) values ('1003', 'stretchable');
insert into ProductFeatures (SKU, feature) values ('1004', 'breathable');
insert into ProductFeatures (SKU, feature) values ('1005', 'UV-resistant');
insert into ProductFeatures (SKU, feature) values ('1006', 'wrinkle-free');
insert into ProductFeatures (SKU, feature) values ('1007', 'stain-resistant');
insert into ProductFeatures (SKU, feature) values ('1008', 'recycled materials');
insert into ProductFeatures (SKU, feature) values ('1009', 'lightweight');
insert into ProductFeatures (SKU, feature) values ('1010', 'moisture-wicking');
insert into ProductFeatures (SKU, feature) values ('1011', 'vegan');
insert into ProductFeatures (SKU, feature) values ('1012', 'quick-dry');
insert into ProductFeatures (SKU, feature) values ('1013', 'odor-resistant');
insert into ProductFeatures (SKU, feature) values ('1014', 'insulated');
insert into ProductFeatures (SKU, feature) values ('1015', 'hypoallergenic');
insert into ProductFeatures (SKU, feature) values ('1016', 'adjustable fit');
insert into ProductFeatures (SKU, feature) values ('1017', 'machine-washable');
insert into ProductFeatures (SKU, feature) values ('1018', 'padded');
insert into ProductFeatures (SKU, feature) values ('1019', 'detachable hood');
insert into ProductFeatures (SKU, feature) values ('1020', 'thermal-regulating');
insert into ProductFeatures (SKU, feature) values ('1021', 'eco-friendly dyes');
insert into ProductFeatures (SKU, feature) values ('1022', 'fade-resistant');
insert into ProductFeatures (SKU, feature) values ('1023', 'high-visibility');
insert into ProductFeatures (SKU, feature) values ('1024', 'stretch waistband');
insert into ProductFeatures (SKU, feature) values ('1025', 'packable');
insert into ProductFeatures (SKU, feature) values ('1026', 'convertible');
insert into ProductFeatures (SKU, feature) values ('1027', 'reinforced seams');
insert into ProductFeatures (SKU, feature) values ('1028', 'thermal insulation');
insert into ProductFeatures (SKU, feature) values ('1029', 'anti-bacterial');
insert into ProductFeatures (SKU, feature) values ('1030', 'soft-touch');
insert into ProductFeatures (SKU, feature) values ('1031', 'reflective details');
insert into ProductFeatures (SKU, feature) values ('1032', 'abrasion-resistant');
insert into ProductFeatures (SKU, feature) values ('1033', 'odor control');
insert into ProductFeatures (SKU, feature) values ('1034', 'wrinkle-resistant');
insert into ProductFeatures (SKU, feature) values ('1035', 'thermal lined');
insert into ProductFeatures (SKU, feature) values ('1036', 'wind-resistant');
insert into ProductFeatures (SKU, feature) values ('1037', 'sweatproof');
insert into ProductFeatures (SKU, feature) values ('1038', 'reversible');
insert into ProductFeatures (SKU, feature) values ('1039', 'biodegradable');
insert into ProductFeatures (SKU, feature) values ('1040', 'scratch-resistant');
insert into ProductFeatures (SKU, feature) values ('1041', 'fade-proof');
insert into ProductFeatures (SKU, feature) values ('1042', 'cooling technology');
insert into ProductFeatures (SKU, feature) values ('1043', 'soft lining');
insert into ProductFeatures (SKU, feature) values ('1044', 'non-slip');
insert into ProductFeatures (SKU, feature) values ('1045', 'shock-absorbing');
insert into ProductFeatures (SKU, feature) values ('1046', 'ventilated');
insert into ProductFeatures (SKU, feature) values ('1047', 'featherweight');
insert into ProductFeatures (SKU, feature) values ('1048', 'multi-pocket');
insert into ProductFeatures (SKU, feature) values ('1049', 'ultra-soft');
insert into ProductFeatures (SKU, feature) values ('1050', 'zippered pockets');
insert into ProductFeatures (SKU, feature) values ('1051', 'double-stitched');
insert into ProductFeatures (SKU, feature) values ('1052', 'air-permeable');
insert into ProductFeatures (SKU, feature) values ('1053', 'elastic cuffs');
insert into ProductFeatures (SKU, feature) values ('1054', 'inner fleece');
insert into ProductFeatures (SKU, feature) values ('1055', 'durable water-repellent');
insert into ProductFeatures (SKU, feature) values ('1056', 'removable sleeves');
insert into ProductFeatures (SKU, feature) values ('1057', 'snag-resistant');
insert into ProductFeatures (SKU, feature) values ('1058', 'low impact production');
insert into ProductFeatures (SKU, feature) values ('1059', 'easy care');
insert into ProductFeatures (SKU, feature) values ('1060', 'slim fit');
insert into ProductFeatures (SKU, feature) values ('1061', 'classic fit');
insert into ProductFeatures (SKU, feature) values ('1062', 'loose fit');
insert into ProductFeatures (SKU, feature) values ('1063', 'seamless design');
insert into ProductFeatures (SKU, feature) values ('1064', 'tagless');
insert into ProductFeatures (SKU, feature) values ('1065', 'double-layered');
insert into ProductFeatures (SKU, feature) values ('1066', 'high-rise');
insert into ProductFeatures (SKU, feature) values ('1067', 'mid-rise');
insert into ProductFeatures (SKU, feature) values ('1068', 'low-rise');
insert into ProductFeatures (SKU, feature) values ('1069', 'wide-leg');
insert into ProductFeatures (SKU, feature) values ('1070', 'tapered');
insert into ProductFeatures (SKU, feature) values ('1071', 'bootcut');
insert into ProductFeatures (SKU, feature) values ('1072', 'water-resistant zippers');
insert into ProductFeatures (SKU, feature) values ('1073', 'ribbed cuffs');
insert into ProductFeatures (SKU, feature) values ('1074', 'high compression');
insert into ProductFeatures (SKU, feature) values ('1075', 'low compression');
insert into ProductFeatures (SKU, feature) values ('1076', 'eco-insulation');
insert into ProductFeatures (SKU, feature) values ('1077', 'breathable mesh');
insert into ProductFeatures (SKU, feature) values ('1078', 'mesh panels');
insert into ProductFeatures (SKU, feature) values ('1079', 'water-repellent fabric');
insert into ProductFeatures (SKU, feature) values ('1080', 'sustainable cotton');
insert into ProductFeatures (SKU, feature) values ('1081', 'plant-based fibers');
insert into ProductFeatures (SKU, feature) values ('1082', 'heat-sealed seams');
insert into ProductFeatures (SKU, feature) values ('1083', 'magnetic closures');
insert into ProductFeatures (SKU, feature) values ('1084', 'adjustable straps');
insert into ProductFeatures (SKU, feature) values ('1085', 'snap buttons');
insert into ProductFeatures (SKU, feature) values ('1086', 'removable liners');
insert into ProductFeatures (SKU, feature) values ('1087', 'insulated padding');
insert into ProductFeatures (SKU, feature) values ('1088', 'shrink-resistant');
insert into ProductFeatures (SKU, feature) values ('1089', 'thermoregulation');
insert into ProductFeatures (SKU, feature) values ('1090', 'ultra-breathable');
insert into ProductFeatures (SKU, feature) values ('1091', 'colorfast');
insert into ProductFeatures (SKU, feature) values ('1092', 'eco-certified');
insert into ProductFeatures (SKU, feature) values ('1093', 'anti-odor');
insert into ProductFeatures (SKU, feature) values ('1094', 'light-insulating');
insert into ProductFeatures (SKU, feature) values ('1095', 'smooth texture');
insert into ProductFeatures (SKU, feature) values ('1096', 'carbon-neutral');
insert into ProductFeatures (SKU, feature) values ('1097', 'upcycled fibers');
insert into ProductFeatures (SKU, feature) values ('1098', 'natural dyes');
insert into ProductFeatures (SKU, feature) values ('1099', 'non-toxic materials');
insert into ProductFeatures (SKU, feature) values ('1100', 'multi-season wear');
insert into ProductFeatures (SKU, feature) values ('1101', 'thermal technology');
insert into ProductFeatures (SKU, feature) values ('1102', 'bio-based fabric');
insert into ProductFeatures (SKU, feature) values ('1103', 'seasonal adaptability');
insert into ProductFeatures (SKU, feature) values ('1104', 'hidden pockets');
insert into ProductFeatures (SKU, feature) values ('1105', 'anti-wrinkle technology');
insert into ProductFeatures (SKU, feature) values ('1106', 'crease-resistant');
insert into ProductFeatures (SKU, feature) values ('1107', 'double-breasted');
insert into ProductFeatures (SKU, feature) values ('1108', 'high-density fabric');
insert into ProductFeatures (SKU, feature) values ('1109', 'pilling resistant');
insert into ProductFeatures (SKU, feature) values ('1110', 'storm flaps');
insert into ProductFeatures (SKU, feature) values ('1111', 'thermal fleece lining');
insert into ProductFeatures (SKU, feature) values ('1112', 'quick-release buckles');
insert into ProductFeatures (SKU, feature) values ('1113', 'self-healing fabric');
insert into ProductFeatures (SKU, feature) values ('1114', 'detachable lining');
insert into ProductFeatures (SKU, feature) values ('1115', 'integrated belt');
insert into ProductFeatures (SKU, feature) values ('1116', 'weatherproof');
insert into ProductFeatures (SKU, feature) values ('1117', 'durable stretch');
insert into ProductFeatures (SKU, feature) values ('1118', 'anti-static');
insert into ProductFeatures (SKU, feature) values ('1119', 'interchangeable');
insert into ProductFeatures (SKU, feature) values ('1120', 'sweat-wicking technology');
insert into ProductFeatures (SKU, feature) values ('1121', 'elastic waistband');
insert into ProductFeatures (SKU, feature) values ('1122', 'recycled polyester');
insert into ProductFeatures (SKU, feature) values ('1123', 'ventilation panels');
insert into ProductFeatures (SKU, feature) values ('1124', 'fashion-forward');
insert into ProductFeatures (SKU, feature) values ('1125', 'light-reflective');
insert into ProductFeatures (SKU, feature) values ('1126', 'moisture regulation');
insert into ProductFeatures (SKU, feature) values ('1127', 'soft hand-feel');
insert into ProductFeatures (SKU, feature) values ('1128', 'fine-knit');
insert into ProductFeatures (SKU, feature) values ('1129', 'multi-way wear');
insert into ProductFeatures (SKU, feature) values ('1130', 'natural stretch');
insert into ProductFeatures (SKU, feature) values ('1131', 'shockproof');
insert into ProductFeatures (SKU, feature) values ('1132', 'quick-release zippers');
insert into ProductFeatures (SKU, feature) values ('1133', 'energy-efficient production');
insert into ProductFeatures (SKU, feature) values ('1134', 'athletic cut');
insert into ProductFeatures (SKU, feature) values ('1135', 'reinforced heels');
insert into ProductFeatures (SKU, feature) values ('1136', 'memory foam padding');
insert into ProductFeatures (SKU, feature) values ('1137', 'built-in support');
insert into ProductFeatures (SKU, feature) values ('1138', 'recycled wool');
insert into ProductFeatures (SKU, feature) values ('1139', 'compact storage');
insert into ProductFeatures (SKU, feature) values ('1140', 'ultra-durable');
insert into ProductFeatures (SKU, feature) values ('1141', 'softshell');
insert into ProductFeatures (SKU, feature) values ('1142', 'heat-retaining');
insert into ProductFeatures (SKU, feature) values ('1143', 'zero-waste manufacturing');
insert into ProductFeatures (SKU, feature) values ('1144', 'natural fibers');
insert into ProductFeatures (SKU, feature) values ('1145', 'insulating core');
insert into ProductFeatures (SKU, feature) values ('1146', 'seam-sealed');
insert into ProductFeatures (SKU, feature) values ('1147', 'comfort fit');
insert into ProductFeatures (SKU, feature) values ('1148', 'seamless');
insert into ProductFeatures (SKU, feature) values ('1149', 'bamboo blend');
insert into ProductFeatures (SKU, feature) values ('1150', 'eco-conscious');
