USE db;
create table VirtualEvent (
                              eventID INT,
                              managerID INT,
                              adID INT,
                              name VARCHAR(50)
);

insert into VirtualEvent (eventID, managerID, adID, name) values (1, 1, 1, 'Summer Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (2, 2, 2, 'Winter Clearance');
insert into VirtualEvent (eventID, managerID, adID, name) values (3, 3, 3, 'Black Friday Deals');
insert into VirtualEvent (eventID, managerID, adID, name) values (4, 4, 4, 'Holiday Savings Event');
insert into VirtualEvent (eventID, managerID, adID, name) values (5, 5, 5, 'End of Season Offers');
insert into VirtualEvent (eventID, managerID, adID, name) values (6, 1, 6, 'Flash Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (7, 2, 7, 'VIP Member Event');
insert into VirtualEvent (eventID, managerID, adID, name) values (8, 3, 8, 'Summer Clearance');
insert into VirtualEvent (eventID, managerID, adID, name) values (9, 4, 9, 'Spring Discount Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (10, 5, 10, 'Exclusive Offer');
insert into VirtualEvent (eventID, managerID, adID, name) values (11, 1, 11, 'Buy One Get One Free');
insert into VirtualEvent (eventID, managerID, adID, name) values (12, 2, 12, 'Seasonal Specials');
insert into VirtualEvent (eventID, managerID, adID, name) values (13, 3, 13, 'Mega Discount Day');
insert into VirtualEvent (eventID, managerID, adID, name) values (14, 4, 14, 'Member Rewards Event');
insert into VirtualEvent (eventID, managerID, adID, name) values (15, 5, 15, 'Weekend Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (16, 1, 16, 'Gift Card Giveaway');
insert into VirtualEvent (eventID, managerID, adID, name) values (17, 2, 17, 'Cyber Monday Deals');
insert into VirtualEvent (eventID, managerID, adID, name) values (18, 3, 18, 'New Year Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (19, 4, 19, 'Back to School Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (20, 5, 20, 'Early Bird Specials');
insert into VirtualEvent (eventID, managerID, adID, name) values (21, 1, 21, 'Weekly Discounts');
insert into VirtualEvent (eventID, managerID, adID, name) values (22, 2, 22, 'End of Year Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (23, 3, 23, 'Holiday Sale Extravaganza');
insert into VirtualEvent (eventID, managerID, adID, name) values (24, 4, 24, 'Spring Festival Deals');
insert into VirtualEvent (eventID, managerID, adID, name) values (25, 5, 25, 'Exclusive Holiday Offers');
insert into VirtualEvent (eventID, managerID, adID, name) values (26, 1, 26, 'Flash Discount Weekend');
insert into VirtualEvent (eventID, managerID, adID, name) values (27, 2, 27, 'Shop and Save');
insert into VirtualEvent (eventID, managerID, adID, name) values (28, 3, 28, 'Weekend Madness');
insert into VirtualEvent (eventID, managerID, adID, name) values (29, 4, 29, 'Midseason Clearance');
insert into VirtualEvent (eventID, managerID, adID, name) values (30, 5, 30, 'Special Promotion Event');
insert into VirtualEvent (eventID, managerID, adID, name) values (31, 1, 31, 'Buy More, Save More');
insert into VirtualEvent (eventID, managerID, adID, name) values (32, 2, 32, 'Happy Hour Deals');
insert into VirtualEvent (eventID, managerID, adID, name) values (33, 3, 33, 'Holiday Countdown Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (34, 4, 34, 'Christmas in July');
insert into VirtualEvent (eventID, managerID, adID, name) values (35, 5, 35, 'Sneak Peek Offers');
insert into VirtualEvent (eventID, managerID, adID, name) values (36, 1, 36, 'Flash Sale Alert');
insert into VirtualEvent (eventID, managerID, adID, name) values (37, 2, 37, 'Midweek Deals');
insert into VirtualEvent (eventID, managerID, adID, name) values (38, 3, 38, 'Holiday Previews');
insert into VirtualEvent (eventID, managerID, adID, name) values (39, 4, 39, 'Winter Wonderland Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (40, 5, 40, 'Super Savings Event');
insert into VirtualEvent (eventID, managerID, adID, name) values (41, 1, 41, 'Weekend Blowout');
insert into VirtualEvent (eventID, managerID, adID, name) values (42, 2, 42, 'Limited Time Offers');
insert into VirtualEvent (eventID, managerID, adID, name) values (43, 3, 43, 'End of Month Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (44, 4, 44, 'Birthday Sale Bash');
insert into VirtualEvent (eventID, managerID, adID, name) values (45, 5, 45, 'VIP Member Preview');
insert into VirtualEvent (eventID, managerID, adID, name) values (46, 1, 46, 'Seasonal Event Launch');
insert into VirtualEvent (eventID, managerID, adID, name) values (47, 2, 47, 'Labor Day Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (48, 3, 48, 'Flash Deal Frenzy');
insert into VirtualEvent (eventID, managerID, adID, name) values (49, 4, 49, 'Exclusive Summer Event');
insert into VirtualEvent (eventID, managerID, adID, name) values (50, 5, 50, 'Surprise Flash Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (51, 1, 51, 'Summer Kickoff Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (52, 2, 52, 'Autumn Clearance');
insert into VirtualEvent (eventID, managerID, adID, name) values (53, 3, 53, 'Winter Wonderland');
insert into VirtualEvent (eventID, managerID, adID, name) values (54, 4, 54, 'Back to School Specials');
insert into VirtualEvent (eventID, managerID, adID, name) values (55, 5, 55, 'Early Access Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (56, 1, 56, 'Cyber Week Deals');
insert into VirtualEvent (eventID, managerID, adID, name) values (57, 2, 57, 'Flash Discount Hour');
insert into VirtualEvent (eventID, managerID, adID, name) values (58, 3, 58, 'Spring Launch Event');
insert into VirtualEvent (eventID, managerID, adID, name) values (59, 4, 59, 'Fallen Leaves Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (60, 5, 60, 'Thanksgiving Special');
insert into VirtualEvent (eventID, managerID, adID, name) values (61, 1, 61, 'Super Sunday Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (62, 2, 62, 'Holiday Kickoff Event');
insert into VirtualEvent (eventID, managerID, adID, name) values (63, 3, 63, 'Fall Fashion Fest');
insert into VirtualEvent (eventID, managerID, adID, name) values (64, 4, 64, 'New Year Countdown Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (65, 5, 65, 'Exclusive Online Offers');
insert into VirtualEvent (eventID, managerID, adID, name) values (66, 1, 66, 'Pre-Christmas Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (67, 2, 67, 'Special Holiday Event');
insert into VirtualEvent (eventID, managerID, adID, name) values (68, 3, 68, 'Flash Sale Saturday');
insert into VirtualEvent (eventID, managerID, adID, name) values (69, 4, 69, 'Pre-Spring Deals');
insert into VirtualEvent (eventID, managerID, adID, name) values (70, 5, 70, 'Weekend Bargain Blast');
insert into VirtualEvent (eventID, managerID, adID, name) values (71, 1, 71, 'Black Friday Preview');
insert into VirtualEvent (eventID, managerID, adID, name) values (72, 2, 72, 'Thanksgiving Countdown');
insert into VirtualEvent (eventID, managerID, adID, name) values (73, 3, 73, 'Annual Summer Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (74, 4, 74, 'Labor Day Weekend Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (75, 5, 75, 'Christmas Gift Guide');
insert into VirtualEvent (eventID, managerID, adID, name) values (76, 1, 76, 'Midweek Flash Deals');
insert into VirtualEvent (eventID, managerID, adID, name) values (77, 2, 77, 'Autumn Clearance Event');
insert into VirtualEvent (eventID, managerID, adID, name) values (78, 3, 78, 'Winter Essentials Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (79, 4, 79, 'Spring Sneak Peek');
insert into VirtualEvent (eventID, managerID, adID, name) values (80, 5, 80, 'Winter Holiday Specials');
insert into VirtualEvent (eventID, managerID, adID, name) values (81, 1, 81, 'Seasonal Shopping Spree');
insert into VirtualEvent (eventID, managerID, adID, name) values (82, 2, 82, 'Exclusive VIP Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (83, 3, 83, 'Holiday Shopping Event');
insert into VirtualEvent (eventID, managerID, adID, name) values (84, 4, 84, 'Year-End Blowout');
insert into VirtualEvent (eventID, managerID, adID, name) values (85, 5, 85, 'New Year Clearance');
insert into VirtualEvent (eventID, managerID, adID, name) values (86, 1, 86, 'Fifty Percent Off Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (87, 2, 87, 'End of Month Specials');
insert into VirtualEvent (eventID, managerID, adID, name) values (88, 3, 88, 'Summer Flash Offers');
insert into VirtualEvent (eventID, managerID, adID, name) values (89, 4, 89, 'Weekend Discount Frenzy');
insert into VirtualEvent (eventID, managerID, adID, name) values (90, 5, 90, 'Super Savings Extravaganza');
insert into VirtualEvent (eventID, managerID, adID, name) values (91, 1, 91, 'Special Winter Deals');
insert into VirtualEvent (eventID, managerID, adID, name) values (92, 2, 92, 'Flash Friday Offers');
insert into VirtualEvent (eventID, managerID, adID, name) values (93, 3, 93, 'Big Spring Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (94, 4, 94, 'Festive Weekend Event');
insert into VirtualEvent (eventID, managerID, adID, name) values (95, 5, 95, 'Exclusive Pre-Order Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (96, 1, 96, 'Black Friday Bonanza');
insert into VirtualEvent (eventID, managerID, adID, name) values (97, 2, 97, 'Boxing Day Event');
insert into VirtualEvent (eventID, managerID, adID, name) values (98, 3, 98, 'Christmas Mega Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (99, 4, 99, 'New Year Countdown Deals');
insert into VirtualEvent (eventID, managerID, adID, name) values (100, 5, 100, 'Weekend Super Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (101, 1, 101, 'Spring Shopping Spree');
insert into VirtualEvent (eventID, managerID, adID, name) values (102, 2, 102, 'Christmas Countdown');
insert into VirtualEvent (eventID, managerID, adID, name) values (103, 3, 103, 'Pre-Holiday Clearance');
insert into VirtualEvent (eventID, managerID, adID, name) values (104, 4, 104, 'Cyber Week Frenzy');
insert into VirtualEvent (eventID, managerID, adID, name) values (105, 5, 105, 'Halloween Special Offers');
insert into VirtualEvent (eventID, managerID, adID, name) values (106, 1, 106, 'Exclusive Spring Launch');
insert into VirtualEvent (eventID, managerID, adID, name) values (107, 2, 107, 'Winter Holiday Event');
insert into VirtualEvent (eventID, managerID, adID, name) values (108, 3, 108, 'Mid-Year Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (109, 4, 109, 'Mega Christmas Deals');
insert into VirtualEvent (eventID, managerID, adID, name) values (110, 5, 110, 'Black Friday Countdown');
insert into VirtualEvent (eventID, managerID, adID, name) values (111, 1, 111, 'New Year Mega Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (112, 2, 112, 'Flash Sale Weekend');
insert into VirtualEvent (eventID, managerID, adID, name) values (113, 3, 113, 'Autumn Fashion Week');
insert into VirtualEvent (eventID, managerID, adID, name) values (114, 4, 114, 'VIP Shopping Day');
insert into VirtualEvent (eventID, managerID, adID, name) values (115, 5, 115, 'Summer Super Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (116, 1, 116, 'Christmas Sale Preview');
insert into VirtualEvent (eventID, managerID, adID, name) values (117, 2, 117, 'Winter Clearance Rush');
insert into VirtualEvent (eventID, managerID, adID, name) values (118, 3, 118, 'End of Year Deals');
insert into VirtualEvent (eventID, managerID, adID, name) values (119, 4, 119, 'Valentine’s Day Special');
insert into VirtualEvent (eventID, managerID, adID, name) values (120, 5, 120, 'Holiday Gift Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (121, 1, 121, 'Seasonal Discount Days');
insert into VirtualEvent (eventID, managerID, adID, name) values (122, 2, 122, 'Pre-Holiday Savings');
insert into VirtualEvent (eventID, managerID, adID, name) values (123, 3, 123, 'Post-New Year Sale');
insert into VirtualEvent (eventID, managerID, adID, name) values (124, 4, 124, 'Exclusive Member Event');
insert into VirtualEvent (eventID, managerID, adID, name) values (125, 5, 125, 'Winter Warm-Up Deals');
